info:
  app:
    name: JVM Bloggers
    description: Application to spread info about polish blogging JVM Developers

spring:
  mandatory-file-encoding: UTF-8 
  jpa.hibernate.ddl-auto: validate
liquibase.change-log: classpath:db/changelog/db.changelog.xml

bloggers.data.file.url: https://raw.githubusercontent.com/tdziurko/jvm-bloggers/master/bloggers.json
companies.data.file.url: https://raw.githubusercontent.com/tdziurko/jvm-bloggers/master/companies.json

# Logging
logging.level.root: INFO
logging.level.pl.tomaszdziurko.jvm_bloggers: DEBUG