spring:
  datasource:
    url: "ENC(K9wJPr6wc7CuKLxnm0+tk+sfS0O4rr725+lSEvBwRqPv3o62c7kx/vrgWlK2DRNL+OXYz6JG02XvXgHJCVMPNX6OnKCJKNs2:)"
    username: "ENC(UCI18sY7gx2IG8jU2w3/zcCxE80YLmTfFIjfmiw/IWc=)"
    password: "ENC(paRXsy9M7apHY2C4vvD6Otf4FO40xqdYm/7Ctt+s+58=)"
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

# Mail Configuration
mailing:
  apiKey: "ENC(MDVhnYiewqWfHfbTepYqnvflkaFRXGDveOVONA24uzWeW74zx1wzB/akhnWxL839)"
  fromEmail: "ENC(UwnuhOY69dp6qFvEDHhl45nGY8iIe+wqm5Yk0pyLS9A=)"
  throttleDelayInSeconds: 180