spring:
  datasource:
    url: jdbc:postgresql://database:5432/jvm_bloggers
    username: jvm_bloggers
    password: jvm_bloggers
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

# Mail Configuration
mailing:
  apiKey: "ENC(u+1+9wseBKqW0dNE7IY2pe5ObMHpQX7pFQnNbCMJKVXFthwD5J+38xq6YSQg9JyC)"
  fromEmail: "ENC(UwnuhOY69dp6qFvEDHhl45nGY8iIe+wqm5Yk0pyLS9A=)"