spring:
  datasource:
    url: "ENC(ZJ0Cbdkwou6ZcQv+AHYeHiHg2W1KlWXSxWH0QqO5krixIXlkZAs25hLOP5uaRk/amYa2rN98gT4yI2X19CQGyZ4bYGefdyolelOkHqV4srIwe3PeJg8PrzZ1Bjv+GVy3XLaHiOp0YsE/3KlKpEhfQFgk4DyzIj2iqhX3TlxvDUfLL4yloC7N7dmjCq2kFnDU)"
    username: "ENC(0YHkdTmfzvPg8Fn/IDGxBT73O0+91P2+)"
    password: "ENC(xY3T8LU2Ds3SQAVNqEc6MlS5Wyr2MsSCYd7i/Eu+zpJR3ArKsxUwFg==)"
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

mails.to.send.weekly.summary: "ENC(CwoHVu2Mmv+Ufx9xxMiHB3eA+dRX7GzEL9jWHiXXIuQURfnAiWw/6qHrDDFcfF9z+mIrLZE+QB5u2HUjbu4gu51ZbQHh6g9O61kW/+hrKGdVgKRlCd3az5hvyz7soodPkHc+RPnntGqM3CIUj2fNjol4ZvGpnAd/K4QCbcxJTkWQmKAQL7Y+XzL9s2SQOuCQrsZQXJ3oQTzK3lxHskwFbdQmghM9d4z/6odcd3LcFa5XSz3RIvmzH/IOi6Ew56RL9nIg6QQ4+ekx18QRaJLXfQ7f4YMkLNnpfCDfOVaSJnPPLKssKqthXW5Nu3/4a6W0NOlajpOHOwatl5SlQb/re1MFEmPo98MP)"

# Sendgrid Configuration
sendgrid:
  apiKey: "ENC(RWnXWOykAzWQcKi5pKKYhT4m+CLDtzXIh2NJZgv36gnJg+KA+QK4N33sFnoylTUkQb5y+qFn1iMdhBnoGEVl9/nVkFo1oyVW9f34QbJQdsk=)"
  fromEmail: "ENC(UwnuhOY69dp6qFvEDHhl45nGY8iIe+wqm5Yk0pyLS9A=)"