spring:
  datasource:
    url: "ENC(yh2uq5HPJRZwnEfkQoMpDZWs530ykVmarLsO0PRuWkK+lL4xCbauMYYMVFcsvHTCohrafq13iiYtgOkElV9VGLvx6++x33T3vfq6FAmk2tswIq7303UaCEwx8eZDW4OXmKNBn3rJKAi/aDQTykXzZlccx3pIivToxcsuMH3lnrHbdxPHHIzO6CPfmAXjfigUNCdfz68mdj4=)"
    username: "ENC(u3wLuWd5WFBCQgGd+sTtkgfb7Prwsplp)"
    password: "ENC(2+ePdd1W8rDJvgaqhRJSwp5xAGONYVaTpQxxOAC5bTWtFjkQ9WxCAA==)"
    driver: org.postgresql.Driver
    test-on-borrow: true
    validation-query: SELECT 1

# Mail Configuration
mailing:
  apiKey: "ENC(u+1+9wseBKqW0dNE7IY2pe5ObMHpQX7pFQnNbCMJKVXFthwD5J+38xq6YSQg9JyC)"
  fromEmail: "ENC(UwnuhOY69dp6qFvEDHhl45nGY8iIe+wqm5Yk0pyLS9A=)"