name: CI
on:
  pull_request:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12'
      - name: Check
        run: ./gradlew check

  deploy:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JVM
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12'
      - name: Build
        run: ./gradlew build
      - name: Get release or tag
        uses: tenhaus/get-release-or-tag@v2
        id: tag
      - name: Build Docker image and push to Docker Hub
        env:
          IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        run: ./gradlew dockerPush
